"""Конфигурация: Settings, YAML, пути к артефактам."""

from app.config.loader import (
    build_arg_parser,
    load_yaml,
    resolve_device,
    resolve_half,
    resolve_quantize,
    settings_from_sources,
)
from app.config.paths import (
    camera_face_json_path,
    camera_face_npz_path,
    camera_links_json_path,
    cameras_dir,
    detections_json_path,
    face_crops_dir,
    feet_json_path,
    info_json_path,
    json_output_path,
    poses_json_path,
    results_root,
    session_key,
    tracking_json_path,
    tracks_json_path,
    tracklet_frames_json_path,
    tracklet_links_json_path,
    tracklet_pose_cache_path,
    tracklet_reid_json_path,
    tracklet_reid_npz_path,
    tracklet_crops_dir,
    tracklets_json_path,
    video_stem,
    video_work_dir,
)
from app.config.settings import DETECTION_BACKEND_CHOICES, STAGE_CHOICES, TRACKER_CHOICES, NvrSettings, Settings

__all__ = [
    "DETECTION_BACKEND_CHOICES",
    "NvrSettings",
    "STAGE_CHOICES",
    "Settings",
    "TRACKER_CHOICES",
    "build_arg_parser",
    "camera_face_json_path",
    "camera_face_npz_path",
    "camera_links_json_path",
    "cameras_dir",
    "detections_json_path",
    "face_crops_dir",
    "feet_json_path",
    "info_json_path",
    "json_output_path",
    "load_yaml",
    "poses_json_path",
    "resolve_device",
    "resolve_half",
    "resolve_quantize",
    "results_root",
    "session_key",
    "settings_from_sources",
    "tracking_json_path",
    "tracklet_crops_dir",
    "tracklet_frames_json_path",
    "tracklet_links_json_path",
    "tracklet_pose_cache_path",
    "tracklet_reid_json_path",
    "tracklet_reid_npz_path",
    "tracklets_json_path",
    "tracks_json_path",
    "video_stem",
    "video_work_dir",
]
